// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO user_activity (
    user_id, session_id, event_type, element, path, ip_address, user_agent, metadata
) VALUES (
    $3, $4, $1,
    $5, $6,
    $7, $8, $2
)
`

type InsertActivityParams struct {
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
	UserID    *uuid.UUID  `json:"user_id"`
	SessionID *uuid.UUID  `json:"session_id"`
	Element   *string     `json:"element"`
	Path      *string     `json:"path"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.EventType,
		arg.Metadata,
		arg.UserID,
		arg.SessionID,
		arg.Element,
		arg.Path,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listActivityByUser = `-- name: ListActivityByUser :many
SELECT id, user_id, session_id, event_type, element, path, ip_address, user_agent, metadata, created_at FROM user_activity
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityByUserParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListActivityByUser(ctx context.Context, arg ListActivityByUserParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, listActivityByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivity{}
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.EventType,
			&i.Element,
			&i.Path,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT id, user_id, session_id, event_type, element, path, ip_address, user_agent, metadata, created_at FROM user_activity
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentActivityParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, listRecentActivity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivity{}
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.EventType,
			&i.Element,
			&i.Path,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeActivityBefore = `-- name: PurgeActivityBefore :exec
DELETE FROM user_activity WHERE created_at < $1
`

func (q *Queries) PurgeActivityBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeActivityBefore, createdAt)
	return err
}
