// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, prefix, key_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, prefix, key_hash, scopes, last_used_at, last_used_ip, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	KeyHash   string             `json:"key_hash"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, prefix, key_hash, scopes, last_used_at, last_used_ip, expires_at, revoked_at, created_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserAPIKeys = `-- name: ListUserAPIKeys :many
SELECT id, user_id, name, prefix, key_hash, scopes, last_used_at, last_used_ip, expires_at, revoked_at, created_at FROM api_keys
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now(), last_used_ip = $2 WHERE id = $1
`

type TouchAPIKeyParams struct {
	ID         uuid.UUID   `json:"id"`
	LastUsedIp *netip.Addr `json:"last_used_ip"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey, arg.ID, arg.LastUsedIp)
	return err
}
