// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    actor_id, actor_email, action, category, object_type, object_id,
    object_name, result, ip_address, user_agent, browser, os, request_id, metadata
) VALUES (
    $5, $6, $1, $2,
    $7, $8, $9,
    $3, $10, $11,
    $12, $13, $14, $4
)
`

type InsertAuditLogParams struct {
	Action     string      `json:"action"`
	Category   string      `json:"category"`
	Result     string      `json:"result"`
	Metadata   []byte      `json:"metadata"`
	ActorID    *uuid.UUID  `json:"actor_id"`
	ActorEmail *string     `json:"actor_email"`
	ObjectType *string     `json:"object_type"`
	ObjectID   *string     `json:"object_id"`
	ObjectName *string     `json:"object_name"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  *string     `json:"user_agent"`
	Browser    *string     `json:"browser"`
	Os         *string     `json:"os"`
	RequestID  *string     `json:"request_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Action,
		arg.Category,
		arg.Result,
		arg.Metadata,
		arg.ActorID,
		arg.ActorEmail,
		arg.ObjectType,
		arg.ObjectID,
		arg.ObjectName,
		arg.IpAddress,
		arg.UserAgent,
		arg.Browser,
		arg.Os,
		arg.RequestID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_email, action, category, object_type, object_id, object_name, result, ip_address, user_agent, browser, os, request_id, metadata, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Category,
			&i.ObjectType,
			&i.ObjectID,
			&i.ObjectName,
			&i.Result,
			&i.IpAddress,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_id, actor_email, action, category, object_type, object_id, object_name, result, ip_address, user_agent, browser, os, request_id, metadata, created_at FROM audit_logs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorID *uuid.UUID `json:"actor_id"`
	Limit   int32      `json:"limit"`
	Offset  int32      `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Category,
			&i.ObjectType,
			&i.ObjectID,
			&i.ObjectName,
			&i.Result,
			&i.IpAddress,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByCategory = `-- name: ListAuditLogsByCategory :many
SELECT id, actor_id, actor_email, action, category, object_type, object_id, object_name, result, ip_address, user_agent, browser, os, request_id, metadata, created_at FROM audit_logs
WHERE category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByCategory(ctx context.Context, arg ListAuditLogsByCategoryParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Category,
			&i.ObjectType,
			&i.ObjectID,
			&i.ObjectName,
			&i.Result,
			&i.IpAddress,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditLogsBefore = `-- name: PurgeAuditLogsBefore :exec
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) PurgeAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeAuditLogsBefore, createdAt)
	return err
}
