// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDownloadsSince = `-- name: CountDownloadsSince :one
SELECT count(*) FROM downloads WHERE created_at >= $1
`

func (q *Queries) CountDownloadsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countDownloadsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDownload = `-- name: InsertDownload :exec
INSERT INTO downloads (file_id, user_id, share_id, bytes_sent, ip_address, user_agent)
VALUES ($4, $5, $6, $1, $2, $3)
`

type InsertDownloadParams struct {
	BytesSent int64       `json:"bytes_sent"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
	FileID    *uuid.UUID  `json:"file_id"`
	UserID    *uuid.UUID  `json:"user_id"`
	ShareID   *uuid.UUID  `json:"share_id"`
}

func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) error {
	_, err := q.db.Exec(ctx, insertDownload,
		arg.BytesSent,
		arg.IpAddress,
		arg.UserAgent,
		arg.FileID,
		arg.UserID,
		arg.ShareID,
	)
	return err
}

const listRecentDownloadsForUser = `-- name: ListRecentDownloadsForUser :many
SELECT id, file_id, user_id, share_id, bytes_sent, ip_address, user_agent, created_at FROM downloads
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentDownloadsForUserParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
}

func (q *Queries) ListRecentDownloadsForUser(ctx context.Context, arg ListRecentDownloadsForUserParams) ([]Download, error) {
	rows, err := q.db.Query(ctx, listRecentDownloadsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.ShareID,
			&i.BytesSent,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
