// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteFileEmbeddings = `-- name: DeleteFileEmbeddings :exec
DELETE FROM file_embeddings WHERE file_id = $1
`

func (q *Queries) DeleteFileEmbeddings(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileEmbeddings, fileID)
	return err
}

const insertFileEmbedding = `-- name: InsertFileEmbedding :exec
INSERT INTO file_embeddings (file_id, owner_id, chunk_no, content, embedding)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFileEmbeddingParams struct {
	FileID    uuid.UUID `json:"file_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	ChunkNo   int32     `json:"chunk_no"`
	Content   string    `json:"content"`
	Embedding []byte    `json:"embedding"`
}

func (q *Queries) InsertFileEmbedding(ctx context.Context, arg InsertFileEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertFileEmbedding,
		arg.FileID,
		arg.OwnerID,
		arg.ChunkNo,
		arg.Content,
		arg.Embedding,
	)
	return err
}

const listEmbeddingsByOwner = `-- name: ListEmbeddingsByOwner :many
SELECT e.file_id, e.content, e.embedding, f.name
FROM file_embeddings e
JOIN files f ON f.id = e.file_id AND f.deleted_at IS NULL
WHERE e.owner_id = $1
LIMIT $2
`

type ListEmbeddingsByOwnerParams struct {
	OwnerID  uuid.UUID `json:"owner_id"`
	RowLimit int32     `json:"row_limit"`
}

type ListEmbeddingsByOwnerRow struct {
	FileID    uuid.UUID `json:"file_id"`
	Content   string    `json:"content"`
	Embedding []byte    `json:"embedding"`
	Name      string    `json:"name"`
}

func (q *Queries) ListEmbeddingsByOwner(ctx context.Context, arg ListEmbeddingsByOwnerParams) ([]ListEmbeddingsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listEmbeddingsByOwner, arg.OwnerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingsByOwnerRow{}
	for rows.Next() {
		var i ListEmbeddingsByOwnerRow
		if err := rows.Scan(
			&i.FileID,
			&i.Content,
			&i.Embedding,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesNeedingEmbedding = `-- name: ListFilesNeedingEmbedding :many
SELECT t.file_id, t.content, f.owner_id
FROM file_text t
JOIN files f ON f.id = t.file_id AND f.deleted_at IS NULL
LEFT JOIN file_embeddings e ON e.file_id = t.file_id
WHERE e.file_id IS NULL AND length(t.content) > 0
LIMIT $1
`

type ListFilesNeedingEmbeddingRow struct {
	FileID  uuid.UUID `json:"file_id"`
	Content string    `json:"content"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) ListFilesNeedingEmbedding(ctx context.Context, rowLimit int32) ([]ListFilesNeedingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listFilesNeedingEmbedding, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesNeedingEmbeddingRow{}
	for rows.Next() {
		var i ListFilesNeedingEmbeddingRow
		if err := rows.Scan(&i.FileID, &i.Content, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
