// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommonFiles = `-- name: CountCommonFiles :one
SELECT count(*) FROM files WHERE is_common = TRUE AND deleted_at IS NULL
`

func (q *Queries) CountCommonFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCommonFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByFolder = `-- name: CountFilesByFolder :one
SELECT count(*) FROM files
WHERE owner_id = $1
  AND folder_id IS NOT DISTINCT FROM $2
  AND deleted_at IS NULL
`

type CountFilesByFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) CountFilesByFolder(ctx context.Context, arg CountFilesByFolderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByFolder, arg.OwnerID, arg.FolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    owner_id, folder_id, name, extension, mime_type,
    size_bytes, checksum_sha256, storage_key
) VALUES ($1, $8, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id
`

type CreateFileParams struct {
	OwnerID        uuid.UUID  `json:"owner_id"`
	Name           string     `json:"name"`
	Extension      string     `json:"extension"`
	MimeType       string     `json:"mime_type"`
	SizeBytes      int64      `json:"size_bytes"`
	ChecksumSha256 *string    `json:"checksum_sha256"`
	StorageKey     string     `json:"storage_key"`
	FolderID       *uuid.UUID `json:"folder_id"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.OwnerID,
		arg.Name,
		arg.Extension,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StorageKey,
		arg.FolderID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.IsStarred,
		&i.VersionNo,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCommon,
		&i.TransferPending,
		&i.TransferDeadline,
		&i.TransferFrom,
		&i.LegalHold,
		&i.RetainUntil,
		&i.Sensitivity,
		&i.PiiTypes,
		&i.TeamID,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.IsStarred,
		&i.VersionNo,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCommon,
		&i.TransferPending,
		&i.TransferDeadline,
		&i.TransferFrom,
		&i.LegalHold,
		&i.RetainUntil,
		&i.Sensitivity,
		&i.PiiTypes,
		&i.TeamID,
	)
	return i, err
}

const getFileByIDIncludingTrashed = `-- name: GetFileByIDIncludingTrashed :one
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files WHERE id = $1
`

func (q *Queries) GetFileByIDIncludingTrashed(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByIDIncludingTrashed, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.IsStarred,
		&i.VersionNo,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCommon,
		&i.TransferPending,
		&i.TransferDeadline,
		&i.TransferFrom,
		&i.LegalHold,
		&i.RetainUntil,
		&i.Sensitivity,
		&i.PiiTypes,
		&i.TeamID,
	)
	return i, err
}

const hardDeleteFile = `-- name: HardDeleteFile :one
DELETE FROM files WHERE id = $1 RETURNING storage_key
`

func (q *Queries) HardDeleteFile(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, hardDeleteFile, id)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
UPDATE files SET download_count = download_count + 1 WHERE id = $1
`

func (q *Queries) IncrementDownloadCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementDownloadCount, id)
	return err
}

const listAllFilesForBackup = `-- name: ListAllFilesForBackup :many
SELECT f.id, f.owner_id, u.username AS owner_username, u.email AS owner_email,
       f.name, f.storage_key, f.size_bytes, f.checksum_sha256, f.is_common,
       COALESCE(fo.path, '') AS folder_path
FROM files f
JOIN users u ON u.id = f.owner_id
LEFT JOIN folders fo ON fo.id = f.folder_id
WHERE f.deleted_at IS NULL
ORDER BY f.owner_id, f.id
`

type ListAllFilesForBackupRow struct {
	ID             uuid.UUID `json:"id"`
	OwnerID        uuid.UUID `json:"owner_id"`
	OwnerUsername  string    `json:"owner_username"`
	OwnerEmail     string    `json:"owner_email"`
	Name           string    `json:"name"`
	StorageKey     string    `json:"storage_key"`
	SizeBytes      int64     `json:"size_bytes"`
	ChecksumSha256 *string   `json:"checksum_sha256"`
	IsCommon       bool      `json:"is_common"`
	FolderPath     string    `json:"folder_path"`
}

func (q *Queries) ListAllFilesForBackup(ctx context.Context) ([]ListAllFilesForBackupRow, error) {
	rows, err := q.db.Query(ctx, listAllFilesForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllFilesForBackupRow{}
	for rows.Next() {
		var i ListAllFilesForBackupRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OwnerUsername,
			&i.OwnerEmail,
			&i.Name,
			&i.StorageKey,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.IsCommon,
			&i.FolderPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommonFiles = `-- name: ListCommonFiles :many
SELECT f.id, f.owner_id, f.folder_id, f.name, f.extension, f.mime_type, f.size_bytes, f.checksum_sha256, f.storage_key, f.thumbnail_key, f.is_starred, f.version_no, f.download_count, f.created_at, f.updated_at, f.deleted_at, f.is_common, f.transfer_pending, f.transfer_deadline, f.transfer_from, f.legal_hold, f.retain_until, f.sensitivity, f.pii_types, f.team_id, u.full_name AS uploader_name, u.username AS uploader_username,
       (u.avatar_path IS NOT NULL AND u.avatar_path <> '') AS uploader_has_avatar
FROM files f
JOIN users u ON u.id = f.owner_id
WHERE f.is_common = TRUE AND f.deleted_at IS NULL
ORDER BY f.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCommonFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCommonFilesRow struct {
	ID                uuid.UUID          `json:"id"`
	OwnerID           uuid.UUID          `json:"owner_id"`
	FolderID          *uuid.UUID         `json:"folder_id"`
	Name              string             `json:"name"`
	Extension         string             `json:"extension"`
	MimeType          string             `json:"mime_type"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    *string            `json:"checksum_sha256"`
	StorageKey        string             `json:"storage_key"`
	ThumbnailKey      *string            `json:"thumbnail_key"`
	IsStarred         bool               `json:"is_starred"`
	VersionNo         int32              `json:"version_no"`
	DownloadCount     int64              `json:"download_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	IsCommon          bool               `json:"is_common"`
	TransferPending   bool               `json:"transfer_pending"`
	TransferDeadline  pgtype.Timestamptz `json:"transfer_deadline"`
	TransferFrom      *uuid.UUID         `json:"transfer_from"`
	LegalHold         bool               `json:"legal_hold"`
	RetainUntil       pgtype.Timestamptz `json:"retain_until"`
	Sensitivity       string             `json:"sensitivity"`
	PiiTypes          []string           `json:"pii_types"`
	TeamID            *uuid.UUID         `json:"team_id"`
	UploaderName      string             `json:"uploader_name"`
	UploaderUsername  string             `json:"uploader_username"`
	UploaderHasAvatar *bool              `json:"uploader_has_avatar"`
}

func (q *Queries) ListCommonFiles(ctx context.Context, arg ListCommonFilesParams) ([]ListCommonFilesRow, error) {
	rows, err := q.db.Query(ctx, listCommonFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommonFilesRow{}
	for rows.Next() {
		var i ListCommonFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
			&i.UploaderName,
			&i.UploaderUsername,
			&i.UploaderHasAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByFolder = `-- name: ListFilesByFolder :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1
  AND folder_id IS NOT DISTINCT FROM $4
  AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListFilesByFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) ListFilesByFolder(ctx context.Context, arg ListFilesByFolderParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByFolder,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.FolderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFiles = `-- name: ListRecentFiles :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentFilesParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListRecentFiles(ctx context.Context, arg ListRecentFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listRecentFiles, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredFiles = `-- name: ListStarredFiles :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1 AND is_starred = TRUE AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListStarredFiles(ctx context.Context, ownerID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listStarredFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrash = `-- name: ListTrash :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT $2 OFFSET $3
`

type ListTrashParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListTrash(ctx context.Context, arg ListTrashParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listTrash, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE files SET folder_id = $2, updated_at = now() WHERE id = $1
`

type MoveFileParams struct {
	ID       uuid.UUID  `json:"id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile, arg.ID, arg.FolderID)
	return err
}

const purgeExpiredTrash = `-- name: PurgeExpiredTrash :many
DELETE FROM files
WHERE deleted_at IS NOT NULL AND deleted_at < $1
RETURNING storage_key
`

func (q *Queries) PurgeExpiredTrash(ctx context.Context, deletedAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, purgeExpiredTrash, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeUserTrash = `-- name: PurgeUserTrash :many
DELETE FROM files
WHERE owner_id = $1 AND deleted_at IS NOT NULL
  AND legal_hold = FALSE
  AND (retain_until IS NULL OR retain_until < now())
RETURNING storage_key, size_bytes, owner_id
`

type PurgeUserTrashRow struct {
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) PurgeUserTrash(ctx context.Context, ownerID uuid.UUID) ([]PurgeUserTrashRow, error) {
	rows, err := q.db.Query(ctx, purgeUserTrash, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurgeUserTrashRow{}
	for rows.Next() {
		var i PurgeUserTrashRow
		if err := rows.Scan(&i.StorageKey, &i.SizeBytes, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameFile = `-- name: RenameFile :exec
UPDATE files SET name = $2, extension = $3, updated_at = now() WHERE id = $1
`

type RenameFileParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Extension string    `json:"extension"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) error {
	_, err := q.db.Exec(ctx, renameFile, arg.ID, arg.Name, arg.Extension)
	return err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE files SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreFile, id)
	return err
}

const searchFiles = `-- name: SearchFiles :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
  AND name ILIKE '%' || $2 || '%'
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type SearchFilesParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Column2 *string   `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles,
		arg.OwnerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
			&i.Sensitivity,
			&i.PiiTypes,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileCommon = `-- name: SetFileCommon :exec
UPDATE files SET is_common = $2, updated_at = now() WHERE id = $1
`

type SetFileCommonParams struct {
	ID       uuid.UUID `json:"id"`
	IsCommon bool      `json:"is_common"`
}

func (q *Queries) SetFileCommon(ctx context.Context, arg SetFileCommonParams) error {
	_, err := q.db.Exec(ctx, setFileCommon, arg.ID, arg.IsCommon)
	return err
}

const setFileStar = `-- name: SetFileStar :exec
UPDATE files SET is_starred = $2, updated_at = now() WHERE id = $1
`

type SetFileStarParams struct {
	ID        uuid.UUID `json:"id"`
	IsStarred bool      `json:"is_starred"`
}

func (q *Queries) SetFileStar(ctx context.Context, arg SetFileStarParams) error {
	_, err := q.db.Exec(ctx, setFileStar, arg.ID, arg.IsStarred)
	return err
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}

const softDeleteFilesInFolders = `-- name: SoftDeleteFilesInFolders :exec
UPDATE files SET deleted_at = now(), updated_at = now()
WHERE folder_id = ANY($1::uuid[])
  AND owner_id = $2
  AND deleted_at IS NULL
  AND legal_hold = FALSE
  AND (retain_until IS NULL OR retain_until < now())
`

type SoftDeleteFilesInFoldersParams struct {
	FolderIds []uuid.UUID `json:"folder_ids"`
	OwnerID   uuid.UUID   `json:"owner_id"`
}

func (q *Queries) SoftDeleteFilesInFolders(ctx context.Context, arg SoftDeleteFilesInFoldersParams) error {
	_, err := q.db.Exec(ctx, softDeleteFilesInFolders, arg.FolderIds, arg.OwnerID)
	return err
}

const sumFileSizesByOwner = `-- name: SumFileSizesByOwner :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SumFileSizesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumFileSizesByOwner, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
