// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filetext.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const hasFileText = `-- name: HasFileText :one
SELECT EXISTS (SELECT 1 FROM file_text WHERE file_id = $1)
`

func (q *Queries) HasFileText(ctx context.Context, fileID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasFileText, fileID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFilesMissingText = `-- name: ListFilesMissingText :many
SELECT f.id, f.storage_key, f.mime_type, f.extension, f.size_bytes
FROM files f
LEFT JOIN file_text t ON t.file_id = f.id
WHERE f.deleted_at IS NULL
  AND t.file_id IS NULL
ORDER BY f.created_at DESC
LIMIT $1
`

type ListFilesMissingTextRow struct {
	ID         uuid.UUID `json:"id"`
	StorageKey string    `json:"storage_key"`
	MimeType   string    `json:"mime_type"`
	Extension  string    `json:"extension"`
	SizeBytes  int64     `json:"size_bytes"`
}

func (q *Queries) ListFilesMissingText(ctx context.Context, limit int32) ([]ListFilesMissingTextRow, error) {
	rows, err := q.db.Query(ctx, listFilesMissingText, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesMissingTextRow{}
	for rows.Next() {
		var i ListFilesMissingTextRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.MimeType,
			&i.Extension,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFileContent = `-- name: SearchFileContent :many
SELECT f.id, f.name, f.extension, f.mime_type, f.size_bytes, f.folder_id,
       f.is_starred, f.version_no, f.download_count, f.created_at, f.updated_at,
       ts_rank(t.tsv, websearch_to_tsquery('english', $1)) AS rank,
       ts_headline('english', t.content, websearch_to_tsquery('english', $1),
                   'MaxFragments=1,MaxWords=18,MinWords=5,StartSel=<<,StopSel=>>') AS snippet
FROM file_text t
JOIN files f ON f.id = t.file_id
WHERE f.owner_id = $2
  AND f.deleted_at IS NULL
  AND t.tsv @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $3
`

type SearchFileContentParams struct {
	Query    string    `json:"query"`
	OwnerID  uuid.UUID `json:"owner_id"`
	RowLimit int32     `json:"row_limit"`
}

type SearchFileContentRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Extension     string             `json:"extension"`
	MimeType      string             `json:"mime_type"`
	SizeBytes     int64              `json:"size_bytes"`
	FolderID      *uuid.UUID         `json:"folder_id"`
	IsStarred     bool               `json:"is_starred"`
	VersionNo     int32              `json:"version_no"`
	DownloadCount int64              `json:"download_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Rank          float32            `json:"rank"`
	Snippet       []byte             `json:"snippet"`
}

func (q *Queries) SearchFileContent(ctx context.Context, arg SearchFileContentParams) ([]SearchFileContentRow, error) {
	rows, err := q.db.Query(ctx, searchFileContent, arg.Query, arg.OwnerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFileContentRow{}
	for rows.Next() {
		var i SearchFileContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.FolderID,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileClassification = `-- name: SetFileClassification :exec
UPDATE files SET sensitivity = $1, pii_types = $2 WHERE id = $3
`

type SetFileClassificationParams struct {
	Sensitivity string    `json:"sensitivity"`
	PiiTypes    []string  `json:"pii_types"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) SetFileClassification(ctx context.Context, arg SetFileClassificationParams) error {
	_, err := q.db.Exec(ctx, setFileClassification, arg.Sensitivity, arg.PiiTypes, arg.ID)
	return err
}

const upsertFileText = `-- name: UpsertFileText :exec
INSERT INTO file_text (file_id, content, tsv, ocr, bytes, lang)
VALUES ($1, $2, to_tsvector('english', $2), $3, $4, 'english')
ON CONFLICT (file_id) DO UPDATE
SET content = EXCLUDED.content,
    tsv = EXCLUDED.tsv,
    ocr = EXCLUDED.ocr,
    bytes = EXCLUDED.bytes,
    extracted_at = now()
`

type UpsertFileTextParams struct {
	FileID  uuid.UUID `json:"file_id"`
	Content string    `json:"content"`
	Ocr     bool      `json:"ocr"`
	Bytes   int64     `json:"bytes"`
}

func (q *Queries) UpsertFileText(ctx context.Context, arg UpsertFileTextParams) error {
	_, err := q.db.Exec(ctx, upsertFileText,
		arg.FileID,
		arg.Content,
		arg.Ocr,
		arg.Bytes,
	)
	return err
}
