// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const countFolderChildren = `-- name: CountFolderChildren :one
SELECT
  (SELECT count(*) FROM folders WHERE parent_id = $1 AND deleted_at IS NULL) +
  (SELECT count(*) FROM files   WHERE folder_id = $1 AND deleted_at IS NULL) AS total
`

func (q *Queries) CountFolderChildren(ctx context.Context, parentID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFolderChildren, parentID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (owner_id, parent_id, name, path, depth)
VALUES ($1, $5, $2, $3, $4)
RETURNING id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at, color, team_id
`

type CreateFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	Name     string     `json:"name"`
	Path     string     `json:"path"`
	Depth    int32      `json:"depth"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.OwnerID,
		arg.Name,
		arg.Path,
		arg.Depth,
		arg.ParentID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Depth,
		&i.SizeBytes,
		&i.IsStarred,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
		&i.TeamID,
	)
	return i, err
}

const getFileByOwnerFolderName = `-- name: GetFileByOwnerFolderName :one
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until, sensitivity, pii_types, team_id FROM files
WHERE owner_id = $1
  AND folder_id IS NOT DISTINCT FROM $3
  AND name = $2 AND deleted_at IS NULL
`

type GetFileByOwnerFolderNameParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	Name     string     `json:"name"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) GetFileByOwnerFolderName(ctx context.Context, arg GetFileByOwnerFolderNameParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByOwnerFolderName, arg.OwnerID, arg.Name, arg.FolderID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.IsStarred,
		&i.VersionNo,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCommon,
		&i.TransferPending,
		&i.TransferDeadline,
		&i.TransferFrom,
		&i.LegalHold,
		&i.RetainUntil,
		&i.Sensitivity,
		&i.PiiTypes,
		&i.TeamID,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at, color, team_id FROM folders WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Depth,
		&i.SizeBytes,
		&i.IsStarred,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
		&i.TeamID,
	)
	return i, err
}

const getFolderByOwnerPath = `-- name: GetFolderByOwnerPath :one
SELECT id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at, color, team_id FROM folders
WHERE owner_id = $1 AND path = $2 AND deleted_at IS NULL
`

type GetFolderByOwnerPathParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Path    string    `json:"path"`
}

func (q *Queries) GetFolderByOwnerPath(ctx context.Context, arg GetFolderByOwnerPathParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByOwnerPath, arg.OwnerID, arg.Path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Depth,
		&i.SizeBytes,
		&i.IsStarred,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
		&i.TeamID,
	)
	return i, err
}

const listFilesInFolder = `-- name: ListFilesInFolder :many
SELECT id, name, storage_key, size_bytes
FROM files
WHERE owner_id = $1 AND folder_id = $2 AND deleted_at IS NULL
`

type ListFilesInFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

type ListFilesInFolderRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
}

func (q *Queries) ListFilesInFolder(ctx context.Context, arg ListFilesInFolderParams) ([]ListFilesInFolderRow, error) {
	rows, err := q.db.Query(ctx, listFilesInFolder, arg.OwnerID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesInFolderRow{}
	for rows.Next() {
		var i ListFilesInFolderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StorageKey,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at, color, team_id FROM folders
WHERE owner_id = $1
  AND parent_id IS NOT DISTINCT FROM $2
  AND deleted_at IS NULL
ORDER BY name ASC
`

type ListFoldersByParentParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.OwnerID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.Depth,
			&i.SizeBytes,
			&i.IsStarred,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Color,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolder = `-- name: MoveFolder :exec
UPDATE folders
SET parent_id = $4, path = $2, depth = $3, updated_at = now()
WHERE id = $1
`

type MoveFolderParams struct {
	ID       uuid.UUID  `json:"id"`
	Path     string     `json:"path"`
	Depth    int32      `json:"depth"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder,
		arg.ID,
		arg.Path,
		arg.Depth,
		arg.ParentID,
	)
	return err
}

const renameFolder = `-- name: RenameFolder :exec
UPDATE folders SET name = $2, path = $3, updated_at = now() WHERE id = $1
`

type RenameFolderParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Path string    `json:"path"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) error {
	_, err := q.db.Exec(ctx, renameFolder, arg.ID, arg.Name, arg.Path)
	return err
}

const setFolderColor = `-- name: SetFolderColor :exec
UPDATE folders SET color = $2, updated_at = now() WHERE id = $1
`

type SetFolderColorParams struct {
	ID    uuid.UUID `json:"id"`
	Color string    `json:"color"`
}

func (q *Queries) SetFolderColor(ctx context.Context, arg SetFolderColorParams) error {
	_, err := q.db.Exec(ctx, setFolderColor, arg.ID, arg.Color)
	return err
}

const setFolderStar = `-- name: SetFolderStar :exec
UPDATE folders SET is_starred = $2, updated_at = now() WHERE id = $1
`

type SetFolderStarParams struct {
	ID        uuid.UUID `json:"id"`
	IsStarred bool      `json:"is_starred"`
}

func (q *Queries) SetFolderStar(ctx context.Context, arg SetFolderStarParams) error {
	_, err := q.db.Exec(ctx, setFolderStar, arg.ID, arg.IsStarred)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFolder, id)
	return err
}

const softDeleteFolders = `-- name: SoftDeleteFolders :exec
UPDATE folders SET deleted_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[]) AND owner_id = $2 AND deleted_at IS NULL
`

type SoftDeleteFoldersParams struct {
	FolderIds []uuid.UUID `json:"folder_ids"`
	OwnerID   uuid.UUID   `json:"owner_id"`
}

func (q *Queries) SoftDeleteFolders(ctx context.Context, arg SoftDeleteFoldersParams) error {
	_, err := q.db.Exec(ctx, softDeleteFolders, arg.FolderIds, arg.OwnerID)
	return err
}

const updateFolderSize = `-- name: UpdateFolderSize :exec
UPDATE folders SET size_bytes = $2, updated_at = now() WHERE id = $1
`

type UpdateFolderSizeParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) UpdateFolderSize(ctx context.Context, arg UpdateFolderSizeParams) error {
	_, err := q.db.Exec(ctx, updateFolderSize, arg.ID, arg.SizeBytes)
	return err
}
