// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const countFolderChildren = `-- name: CountFolderChildren :one
SELECT
  (SELECT count(*) FROM folders WHERE parent_id = $1 AND deleted_at IS NULL) +
  (SELECT count(*) FROM files   WHERE folder_id = $1 AND deleted_at IS NULL) AS total
`

func (q *Queries) CountFolderChildren(ctx context.Context, parentID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFolderChildren, parentID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (owner_id, parent_id, name, path, depth)
VALUES ($1, $5, $2, $3, $4)
RETURNING id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	Name     string     `json:"name"`
	Path     string     `json:"path"`
	Depth    int32      `json:"depth"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.OwnerID,
		arg.Name,
		arg.Path,
		arg.Depth,
		arg.ParentID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Depth,
		&i.SizeBytes,
		&i.IsStarred,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at FROM folders WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Depth,
		&i.SizeBytes,
		&i.IsStarred,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, owner_id, parent_id, name, path, depth, size_bytes, is_starred, is_pinned, created_at, updated_at, deleted_at FROM folders
WHERE owner_id = $1
  AND parent_id IS NOT DISTINCT FROM $2
  AND deleted_at IS NULL
ORDER BY name ASC
`

type ListFoldersByParentParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, arg.OwnerID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.Depth,
			&i.SizeBytes,
			&i.IsStarred,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolder = `-- name: MoveFolder :exec
UPDATE folders
SET parent_id = $4, path = $2, depth = $3, updated_at = now()
WHERE id = $1
`

type MoveFolderParams struct {
	ID       uuid.UUID  `json:"id"`
	Path     string     `json:"path"`
	Depth    int32      `json:"depth"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder,
		arg.ID,
		arg.Path,
		arg.Depth,
		arg.ParentID,
	)
	return err
}

const renameFolder = `-- name: RenameFolder :exec
UPDATE folders SET name = $2, path = $3, updated_at = now() WHERE id = $1
`

type RenameFolderParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Path string    `json:"path"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) error {
	_, err := q.db.Exec(ctx, renameFolder, arg.ID, arg.Name, arg.Path)
	return err
}

const setFolderStar = `-- name: SetFolderStar :exec
UPDATE folders SET is_starred = $2, updated_at = now() WHERE id = $1
`

type SetFolderStarParams struct {
	ID        uuid.UUID `json:"id"`
	IsStarred bool      `json:"is_starred"`
}

func (q *Queries) SetFolderStar(ctx context.Context, arg SetFolderStarParams) error {
	_, err := q.db.Exec(ctx, setFolderStar, arg.ID, arg.IsStarred)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :exec
UPDATE folders SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFolder, id)
	return err
}

const updateFolderSize = `-- name: UpdateFolderSize :exec
UPDATE folders SET size_bytes = $2, updated_at = now() WHERE id = $1
`

type UpdateFolderSizeParams struct {
	ID        uuid.UUID `json:"id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) UpdateFolderSize(ctx context.Context, arg UpdateFolderSizeParams) error {
	_, err := q.db.Exec(ctx, updateFolderSize, arg.ID, arg.SizeBytes)
	return err
}
