// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_history.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const insertLoginHistory = `-- name: InsertLoginHistory :exec
INSERT INTO login_history (
    user_id, email, success, reason, ip_address, user_agent, browser, os
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLoginHistoryParams struct {
	UserID    *uuid.UUID  `json:"user_id"`
	Email     *string     `json:"email"`
	Success   bool        `json:"success"`
	Reason    *string     `json:"reason"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
	Browser   *string     `json:"browser"`
	Os        *string     `json:"os"`
}

func (q *Queries) InsertLoginHistory(ctx context.Context, arg InsertLoginHistoryParams) error {
	_, err := q.db.Exec(ctx, insertLoginHistory,
		arg.UserID,
		arg.Email,
		arg.Success,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
		arg.Browser,
		arg.Os,
	)
	return err
}

const listLoginHistoryForUser = `-- name: ListLoginHistoryForUser :many
SELECT id, user_id, email, success, reason, ip_address, user_agent, browser, os, created_at FROM login_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLoginHistoryForUserParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListLoginHistoryForUser(ctx context.Context, arg ListLoginHistoryForUserParams) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, listLoginHistoryForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginHistory{}
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Success,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLoginHistory = `-- name: ListRecentLoginHistory :many
SELECT id, user_id, email, success, reason, ip_address, user_agent, browser, os, created_at FROM login_history
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentLoginHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentLoginHistory(ctx context.Context, arg ListRecentLoginHistoryParams) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, listRecentLoginHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginHistory{}
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Success,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.Browser,
			&i.Os,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
