// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sftpdb

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp *netip.Addr        `json:"last_used_ip"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	ActorEmail *string            `json:"actor_email"`
	Action     string             `json:"action"`
	Category   string             `json:"category"`
	ObjectType *string            `json:"object_type"`
	ObjectID   *string            `json:"object_id"`
	ObjectName *string            `json:"object_name"`
	Result     string             `json:"result"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	Browser    *string            `json:"browser"`
	Os         *string            `json:"os"`
	RequestID  *string            `json:"request_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Department struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Download struct {
	ID        uuid.UUID          `json:"id"`
	FileID    *uuid.UUID         `json:"file_id"`
	UserID    *uuid.UUID         `json:"user_id"`
	ShareID   *uuid.UUID         `json:"share_id"`
	BytesSent int64              `json:"bytes_sent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FileID    *uuid.UUID         `json:"file_id"`
	FolderID  *uuid.UUID         `json:"folder_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID               uuid.UUID          `json:"id"`
	OwnerID          uuid.UUID          `json:"owner_id"`
	FolderID         *uuid.UUID         `json:"folder_id"`
	Name             string             `json:"name"`
	Extension        string             `json:"extension"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	ChecksumSha256   *string            `json:"checksum_sha256"`
	StorageKey       string             `json:"storage_key"`
	ThumbnailKey     *string            `json:"thumbnail_key"`
	IsStarred        bool               `json:"is_starred"`
	VersionNo        int32              `json:"version_no"`
	DownloadCount    int64              `json:"download_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	IsCommon         bool               `json:"is_common"`
	TransferPending  bool               `json:"transfer_pending"`
	TransferDeadline pgtype.Timestamptz `json:"transfer_deadline"`
	TransferFrom     *uuid.UUID         `json:"transfer_from"`
	LegalHold        bool               `json:"legal_hold"`
	RetainUntil      pgtype.Timestamptz `json:"retain_until"`
}

type FileTag struct {
	FileID uuid.UUID `json:"file_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type FileText struct {
	FileID      uuid.UUID          `json:"file_id"`
	Content     string             `json:"content"`
	Tsv         interface{}        `json:"tsv"`
	Lang        string             `json:"lang"`
	Ocr         bool               `json:"ocr"`
	Bytes       int64              `json:"bytes"`
	ExtractedAt pgtype.Timestamptz `json:"extracted_at"`
}

type FileVersion struct {
	ID             uuid.UUID          `json:"id"`
	FileID         uuid.UUID          `json:"file_id"`
	VersionNo      int32              `json:"version_no"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 *string            `json:"checksum_sha256"`
	StorageKey     string             `json:"storage_key"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Folder struct {
	ID        uuid.UUID          `json:"id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Name      string             `json:"name"`
	Path      string             `json:"path"`
	Depth     int32              `json:"depth"`
	SizeBytes int64              `json:"size_bytes"`
	IsStarred bool               `json:"is_starred"`
	IsPinned  bool               `json:"is_pinned"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Color     string             `json:"color"`
}

type LoginHistory struct {
	ID        uuid.UUID          `json:"id"`
	UserID    *uuid.UUID         `json:"user_id"`
	Email     *string            `json:"email"`
	Success   bool               `json:"success"`
	Reason    *string            `json:"reason"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	Browser   *string            `json:"browser"`
	Os        *string            `json:"os"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Link      *string            `json:"link"`
	IsRead    bool               `json:"is_read"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ResourcePermission struct {
	ID            uuid.UUID          `json:"id"`
	FileID        *uuid.UUID         `json:"file_id"`
	FolderID      *uuid.UUID         `json:"folder_id"`
	GranteeUserID *uuid.UUID         `json:"grantee_user_id"`
	GranteeRoleID *uuid.UUID         `json:"grantee_role_id"`
	CanRead       bool               `json:"can_read"`
	CanWrite      bool               `json:"can_write"`
	CanDelete     bool               `json:"can_delete"`
	CanMove       bool               `json:"can_move"`
	CanShare      bool               `json:"can_share"`
	CanDownload   bool               `json:"can_download"`
	CanUpload     bool               `json:"can_upload"`
	Inherit       bool               `json:"inherit"`
	CreatedBy     *uuid.UUID         `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	IsSystem    bool               `json:"is_system"`
	Priority    int32              `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type SecurityAlert struct {
	ID          uuid.UUID          `json:"id"`
	Type        string             `json:"type"`
	Severity    string             `json:"severity"`
	ActorID     *uuid.UUID         `json:"actor_id"`
	ActorEmail  *string            `json:"actor_email"`
	Summary     string             `json:"summary"`
	EventCount  int32              `json:"event_count"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	Metadata    []byte             `json:"metadata"`
	Resolved    bool               `json:"resolved"`
	ResolvedBy  *uuid.UUID         `json:"resolved_by"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        string             `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	DeviceLabel      *string            `json:"device_label"`
	RememberMe       bool               `json:"remember_me"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID        uuid.UUID          `json:"id"`
	Scope     string             `json:"scope"`
	UserID    *uuid.UUID         `json:"user_id"`
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Share struct {
	ID            uuid.UUID          `json:"id"`
	Token         string             `json:"token"`
	OwnerID       uuid.UUID          `json:"owner_id"`
	FileID        *uuid.UUID         `json:"file_id"`
	FolderID      *uuid.UUID         `json:"folder_id"`
	Permission    string             `json:"permission"`
	PasswordHash  *string            `json:"password_hash"`
	DownloadLimit *int32             `json:"download_limit"`
	DownloadCount int32              `json:"download_count"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ShareRecipient struct {
	ID        uuid.UUID          `json:"id"`
	ShareID   uuid.UUID          `json:"share_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
	Color   string    `json:"color"`
}

type Upload struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	FolderID       *uuid.UUID         `json:"folder_id"`
	Filename       string             `json:"filename"`
	TotalSize      int64              `json:"total_size"`
	ChunkSize      int64              `json:"chunk_size"`
	TotalChunks    int32              `json:"total_chunks"`
	UploadedChunks int32              `json:"uploaded_chunks"`
	ReceivedBytes  int64              `json:"received_bytes"`
	TempKey        string             `json:"temp_key"`
	ChecksumSha256 *string            `json:"checksum_sha256"`
	Status         string             `json:"status"`
	FileID         *uuid.UUID         `json:"file_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UploadChunk struct {
	UploadID   uuid.UUID          `json:"upload_id"`
	ChunkIndex int32              `json:"chunk_index"`
	SizeBytes  int64              `json:"size_bytes"`
	Checksum   *string            `json:"checksum"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	EmployeeID        *string            `json:"employee_id"`
	DepartmentID      *uuid.UUID         `json:"department_id"`
	RoleID            uuid.UUID          `json:"role_id"`
	AvatarPath        *string            `json:"avatar_path"`
	Phone             *string            `json:"phone"`
	StorageQuota      int64              `json:"storage_quota"`
	StorageUsed       int64              `json:"storage_used"`
	IsActive          bool               `json:"is_active"`
	IsLocked          bool               `json:"is_locked"`
	FailedAttempts    int32              `json:"failed_attempts"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	MfaEnabled        bool               `json:"mfa_enabled"`
	MfaSecret         *string            `json:"mfa_secret"`
	MustChangePw      bool               `json:"must_change_pw"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type UserActivity struct {
	ID        int64              `json:"id"`
	UserID    *uuid.UUID         `json:"user_id"`
	SessionID *uuid.UUID         `json:"session_id"`
	EventType string             `json:"event_type"`
	Element   *string            `json:"element"`
	Path      *string            `json:"path"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
