// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddStorageUsed(ctx context.Context, arg AddStorageUsedParams) error
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	CountActiveUsers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetPermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]string, error)
	GetPermissionsForUser(ctx context.Context, id uuid.UUID) ([]string, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetSessionByHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementFailedAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	InsertLoginHistory(ctx context.Context, arg InsertLoginHistoryParams) error
	ListLoginHistoryForUser(ctx context.Context, arg ListLoginHistoryForUserParams) ([]LoginHistory, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRecentLoginHistory(ctx context.Context, arg ListRecentLoginHistoryParams) ([]LoginHistory, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionByHash(ctx context.Context, refreshTokenHash string) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UnlockUser(ctx context.Context, id uuid.UUID) error
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
