// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddStorageUsed(ctx context.Context, arg AddStorageUsedParams) error
	BumpFileContent(ctx context.Context, arg BumpFileContentParams) (File, error)
	ClearAllPendingForUser(ctx context.Context, ownerID uuid.UUID) error
	ClearFilePending(ctx context.Context, arg ClearFilePendingParams) error
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	CompleteUpload(ctx context.Context, arg CompleteUploadParams) error
	// Detection aggregations over the audit stream --------------------------------
	// Groups matching actions by actor within a window, flagging actors at/over the
	// threshold. Pass a set of actions (e.g. ARRAY['file.download']).
	CountActionsByActor(ctx context.Context, arg CountActionsByActorParams) ([]CountActionsByActorRow, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountCommonFiles(ctx context.Context) (int64, error)
	CountDownloadsSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountFailedLoginsByEmail(ctx context.Context, arg CountFailedLoginsByEmailParams) ([]CountFailedLoginsByEmailRow, error)
	CountFilesByFolder(ctx context.Context, arg CountFilesByFolderParams) (int64, error)
	CountFilesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountFolderChildren(ctx context.Context, parentID *uuid.UUID) (int32, error)
	CountFoldersByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountInheritedFiles(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountRecentNotifications(ctx context.Context, arg CountRecentNotificationsParams) (int64, error)
	CountTrashByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUnresolvedAlerts(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateExpiredShares(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredUploads(ctx context.Context) ([]DeleteExpiredUploadsRow, error)
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetFileByID(ctx context.Context, id uuid.UUID) (File, error)
	GetFileByIDIncludingTrashed(ctx context.Context, id uuid.UUID) (File, error)
	GetFileByOwnerFolderName(ctx context.Context, arg GetFileByOwnerFolderNameParams) (File, error)
	GetFileGrant(ctx context.Context, arg GetFileGrantParams) (GetFileGrantRow, error)
	GetFileVersion(ctx context.Context, arg GetFileVersionParams) (GetFileVersionRow, error)
	GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error)
	GetFolderByOwnerPath(ctx context.Context, arg GetFolderByOwnerPathParams) (Folder, error)
	GetPermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]string, error)
	GetPermissionsForUser(ctx context.Context, id uuid.UUID) ([]string, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetSessionByHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetShareByToken(ctx context.Context, token string) (Share, error)
	GetUpload(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUploadForUser(ctx context.Context, arg GetUploadForUserParams) (Upload, error)
	GetUserAvatar(ctx context.Context, id uuid.UUID) (*string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GrantFileToUser(ctx context.Context, arg GrantFileToUserParams) (ResourcePermission, error)
	HardDeleteFile(ctx context.Context, id uuid.UUID) (string, error)
	HasFileText(ctx context.Context, fileID uuid.UUID) (bool, error)
	IncrementDownloadCount(ctx context.Context, id uuid.UUID) error
	IncrementFailedAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	IncrementShareDownload(ctx context.Context, id uuid.UUID) error
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertDownload(ctx context.Context, arg InsertDownloadParams) error
	InsertFileVersion(ctx context.Context, arg InsertFileVersionParams) error
	InsertLoginHistory(ctx context.Context, arg InsertLoginHistoryParams) error
	InsertSecurityAlert(ctx context.Context, arg InsertSecurityAlertParams) (SecurityAlert, error)
	LargestFilesByOwner(ctx context.Context, arg LargestFilesByOwnerParams) ([]File, error)
	ListActivityByUser(ctx context.Context, arg ListActivityByUserParams) ([]UserActivity, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByCategory(ctx context.Context, arg ListAuditLogsByCategoryParams) ([]AuditLog, error)
	ListCommonFiles(ctx context.Context, arg ListCommonFilesParams) ([]ListCommonFilesRow, error)
	ListFileGrants(ctx context.Context, fileID *uuid.UUID) ([]ListFileGrantsRow, error)
	ListFileVersions(ctx context.Context, fileID uuid.UUID) ([]ListFileVersionsRow, error)
	ListFilesByFolder(ctx context.Context, arg ListFilesByFolderParams) ([]File, error)
	ListFilesMissingText(ctx context.Context, limit int32) ([]ListFilesMissingTextRow, error)
	ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error)
	ListInheritedFiles(ctx context.Context, ownerID uuid.UUID) ([]File, error)
	ListLoginHistoryForUser(ctx context.Context, arg ListLoginHistoryForUserParams) ([]LoginHistory, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListReceivedChunks(ctx context.Context, uploadID uuid.UUID) ([]int32, error)
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]UserActivity, error)
	ListRecentDownloadsForUser(ctx context.Context, arg ListRecentDownloadsForUserParams) ([]Download, error)
	ListRecentFiles(ctx context.Context, arg ListRecentFilesParams) ([]File, error)
	ListRecentLoginHistory(ctx context.Context, arg ListRecentLoginHistoryParams) ([]LoginHistory, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSecurityAlerts(ctx context.Context, arg ListSecurityAlertsParams) ([]SecurityAlert, error)
	ListSharedWithMe(ctx context.Context, granteeUserID *uuid.UUID) ([]ListSharedWithMeRow, error)
	ListSharesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Share, error)
	ListStarredFiles(ctx context.Context, ownerID uuid.UUID) ([]File, error)
	ListSuperAdminIDs(ctx context.Context) ([]uuid.UUID, error)
	ListTrash(ctx context.Context, arg ListTrashParams) ([]File, error)
	ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MediaBreakdown(ctx context.Context) ([]MediaBreakdownRow, error)
	MoveFile(ctx context.Context, arg MoveFileParams) error
	MoveFolder(ctx context.Context, arg MoveFolderParams) error
	PendingTransfersByUser(ctx context.Context) ([]PendingTransfersByUserRow, error)
	PurgeActivityBefore(ctx context.Context, createdAt pgtype.Timestamptz) error
	PurgeAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) error
	PurgeExpiredTrash(ctx context.Context, deletedAt pgtype.Timestamptz) ([]string, error)
	ReassignUserFiles(ctx context.Context, arg ReassignUserFilesParams) error
	ReassignUserFolders(ctx context.Context, arg ReassignUserFoldersParams) error
	// Alert lifecycle -------------------------------------------------------------
	RecentAlertExists(ctx context.Context, arg RecentAlertExistsParams) (bool, error)
	RecordChunk(ctx context.Context, arg RecordChunkParams) error
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) error
	// Admin reset: force the user to change it on next login.
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) error
	ResolveSecurityAlert(ctx context.Context, arg ResolveSecurityAlertParams) error
	RestoreFile(ctx context.Context, id uuid.UUID) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeFileGrant(ctx context.Context, arg RevokeFileGrantParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionByHash(ctx context.Context, refreshTokenHash string) error
	RevokeShare(ctx context.Context, arg RevokeShareParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) error
	SearchFileContent(ctx context.Context, arg SearchFileContentParams) ([]SearchFileContentRow, error)
	SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error)
	SetFileCommon(ctx context.Context, arg SetFileCommonParams) error
	SetFileStar(ctx context.Context, arg SetFileStarParams) error
	SetFolderColor(ctx context.Context, arg SetFolderColorParams) error
	SetFolderStar(ctx context.Context, arg SetFolderStarParams) error
	SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error
	SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteFile(ctx context.Context, id uuid.UUID) error
	SoftDeleteFolder(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	StorageByUser(ctx context.Context) ([]StorageByUserRow, error)
	SumFileSizesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	SystemFileCount(ctx context.Context) (int64, error)
	SystemStorageUsed(ctx context.Context) (int64, error)
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UnlockUser(ctx context.Context, id uuid.UUID) error
	UpdateFolderSize(ctx context.Context, arg UpdateFolderSizeParams) error
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertFileText(ctx context.Context, arg UpsertFileTextParams) error
}

var _ Querier = (*Queries)(nil)
