// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, slug, description, is_system, priority)
VALUES ($1, $2, $3, FALSE, $4)
RETURNING id, name, slug, description, is_system, priority, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Priority    int32  `json:"priority"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Priority,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_system = FALSE
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getPermissionsForRole = `-- name: GetPermissionsForRole :many
SELECT p.slug
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.slug
`

func (q *Queries) GetPermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForUser = `-- name: GetPermissionsForUser :many
SELECT p.slug
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN users u ON u.role_id = rp.role_id
WHERE u.id = $1
ORDER BY p.slug
`

func (q *Queries) GetPermissionsForUser(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, slug, description, is_system, priority, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, name, slug, description, is_system, priority, created_at, updated_at FROM roles WHERE slug = $1
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, slug, category, description, created_at FROM permissions ORDER BY category, slug
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, slug, description, is_system, priority, created_at, updated_at FROM roles ORDER BY priority DESC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsSystem,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRolePermissions = `-- name: SetRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1, p.id FROM permissions p WHERE p.slug = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type SetRolePermissionsParams struct {
	RoleID  uuid.UUID `json:"role_id"`
	Column2 []string  `json:"column_2"`
}

func (q *Queries) SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, setRolePermissions, arg.RoleID, arg.Column2)
	return err
}
