// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const setFileLegalHold = `-- name: SetFileLegalHold :exec
UPDATE files SET legal_hold = $1, updated_at = now() WHERE id = $2
`

type SetFileLegalHoldParams struct {
	Hold bool      `json:"hold"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) SetFileLegalHold(ctx context.Context, arg SetFileLegalHoldParams) error {
	_, err := q.db.Exec(ctx, setFileLegalHold, arg.Hold, arg.ID)
	return err
}

const setFileRetention = `-- name: SetFileRetention :exec
UPDATE files SET retain_until = $1, updated_at = now() WHERE id = $2
`

type SetFileRetentionParams struct {
	RetainUntil pgtype.Timestamptz `json:"retain_until"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) SetFileRetention(ctx context.Context, arg SetFileRetentionParams) error {
	_, err := q.db.Exec(ctx, setFileRetention, arg.RetainUntil, arg.ID)
	return err
}
