// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActionsByActor = `-- name: CountActionsByActor :many

SELECT actor_id, actor_email, COUNT(*)::int AS n,
       MIN(created_at) AS first_at, MAX(created_at) AS last_at
FROM audit_logs
WHERE created_at >= $1
  AND action = ANY($2::text[])
  AND actor_email IS NOT NULL
GROUP BY actor_id, actor_email
HAVING COUNT(*) >= $3
`

type CountActionsByActorParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	Actions   []string           `json:"actions"`
	Threshold interface{}        `json:"threshold"`
}

type CountActionsByActorRow struct {
	ActorID    *uuid.UUID  `json:"actor_id"`
	ActorEmail *string     `json:"actor_email"`
	N          int32       `json:"n"`
	FirstAt    interface{} `json:"first_at"`
	LastAt     interface{} `json:"last_at"`
}

// Detection aggregations over the audit stream --------------------------------
// Groups matching actions by actor within a window, flagging actors at/over the
// threshold. Pass a set of actions (e.g. ARRAY['file.download']).
func (q *Queries) CountActionsByActor(ctx context.Context, arg CountActionsByActorParams) ([]CountActionsByActorRow, error) {
	rows, err := q.db.Query(ctx, countActionsByActor, arg.Since, arg.Actions, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActionsByActorRow{}
	for rows.Next() {
		var i CountActionsByActorRow
		if err := rows.Scan(
			&i.ActorID,
			&i.ActorEmail,
			&i.N,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFailedLoginsByEmail = `-- name: CountFailedLoginsByEmail :many
SELECT actor_email, COUNT(*)::int AS n,
       MIN(created_at) AS first_at, MAX(created_at) AS last_at
FROM audit_logs
WHERE created_at >= $1
  AND action = 'auth.login'
  AND result <> 'success'
  AND actor_email IS NOT NULL
GROUP BY actor_email
HAVING COUNT(*) >= $2
`

type CountFailedLoginsByEmailParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	Threshold interface{}        `json:"threshold"`
}

type CountFailedLoginsByEmailRow struct {
	ActorEmail *string     `json:"actor_email"`
	N          int32       `json:"n"`
	FirstAt    interface{} `json:"first_at"`
	LastAt     interface{} `json:"last_at"`
}

func (q *Queries) CountFailedLoginsByEmail(ctx context.Context, arg CountFailedLoginsByEmailParams) ([]CountFailedLoginsByEmailRow, error) {
	rows, err := q.db.Query(ctx, countFailedLoginsByEmail, arg.Since, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFailedLoginsByEmailRow{}
	for rows.Next() {
		var i CountFailedLoginsByEmailRow
		if err := rows.Scan(
			&i.ActorEmail,
			&i.N,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnresolvedAlerts = `-- name: CountUnresolvedAlerts :one
SELECT COUNT(*) FROM security_alerts WHERE resolved = FALSE
`

func (q *Queries) CountUnresolvedAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnresolvedAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSecurityAlert = `-- name: InsertSecurityAlert :one
INSERT INTO security_alerts (type, severity, actor_id, actor_email, summary, event_count, window_start, window_end, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, type, severity, actor_id, actor_email, summary, event_count, window_start, window_end, metadata, resolved, resolved_by, resolved_at, created_at
`

type InsertSecurityAlertParams struct {
	Type        string             `json:"type"`
	Severity    string             `json:"severity"`
	ActorID     *uuid.UUID         `json:"actor_id"`
	ActorEmail  *string            `json:"actor_email"`
	Summary     string             `json:"summary"`
	EventCount  int32              `json:"event_count"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) InsertSecurityAlert(ctx context.Context, arg InsertSecurityAlertParams) (SecurityAlert, error) {
	row := q.db.QueryRow(ctx, insertSecurityAlert,
		arg.Type,
		arg.Severity,
		arg.ActorID,
		arg.ActorEmail,
		arg.Summary,
		arg.EventCount,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Metadata,
	)
	var i SecurityAlert
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.ActorID,
		&i.ActorEmail,
		&i.Summary,
		&i.EventCount,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Metadata,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSecurityAlerts = `-- name: ListSecurityAlerts :many
SELECT id, type, severity, actor_id, actor_email, summary, event_count, window_start, window_end, metadata, resolved, resolved_by, resolved_at, created_at FROM security_alerts
ORDER BY resolved ASC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListSecurityAlertsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSecurityAlerts(ctx context.Context, arg ListSecurityAlertsParams) ([]SecurityAlert, error) {
	rows, err := q.db.Query(ctx, listSecurityAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityAlert{}
	for rows.Next() {
		var i SecurityAlert
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.ActorID,
			&i.ActorEmail,
			&i.Summary,
			&i.EventCount,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Metadata,
			&i.Resolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuperAdminIDs = `-- name: ListSuperAdminIDs :many
SELECT u.id FROM users u
JOIN roles r ON r.id = u.role_id
WHERE r.slug = 'super_admin' AND u.is_active = TRUE AND u.deleted_at IS NULL
`

func (q *Queries) ListSuperAdminIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSuperAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAlertExists = `-- name: RecentAlertExists :one

SELECT EXISTS (
  SELECT 1 FROM security_alerts
  WHERE type = $1 AND actor_email IS NOT DISTINCT FROM $2
    AND created_at >= $3
)
`

type RecentAlertExistsParams struct {
	Type       string             `json:"type"`
	ActorEmail *string            `json:"actor_email"`
	Since      pgtype.Timestamptz `json:"since"`
}

// Alert lifecycle -------------------------------------------------------------
func (q *Queries) RecentAlertExists(ctx context.Context, arg RecentAlertExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentAlertExists, arg.Type, arg.ActorEmail, arg.Since)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const resolveSecurityAlert = `-- name: ResolveSecurityAlert :exec
UPDATE security_alerts
SET resolved = TRUE, resolved_by = $1, resolved_at = now()
WHERE id = $2
`

type ResolveSecurityAlertParams struct {
	ResolvedBy *uuid.UUID `json:"resolved_by"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) ResolveSecurityAlert(ctx context.Context, arg ResolveSecurityAlertParams) error {
	_, err := q.db.Exec(ctx, resolveSecurityAlert, arg.ResolvedBy, arg.ID)
	return err
}
