// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sftpdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, refresh_token_hash, user_agent, ip_address,
    device_label, remember_me, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, device_label, remember_me, expires_at, revoked_at, last_seen_at, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        string             `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	DeviceLabel      *string            `json:"device_label"`
	RememberMe       bool               `json:"remember_me"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.DeviceLabel,
		arg.RememberMe,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now() OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, device_label, remember_me, expires_at, revoked_at, last_seen_at, created_at FROM sessions
WHERE refresh_token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetSessionByHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, device_label, remember_me, expires_at, revoked_at, last_seen_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.DeviceLabel,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, device_label, remember_me, expires_at, revoked_at, last_seen_at, created_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.DeviceLabel,
			&i.RememberMe,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :exec
UPDATE sessions SET revoked_at = now() WHERE refresh_token_hash = $1
`

func (q *Queries) RevokeSessionByHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHash, refreshTokenHash)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE sessions
SET refresh_token_hash = $2, expires_at = $3, last_seen_at = now()
WHERE id = $1
`

type RotateSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
