// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (
    token, owner_id, file_id, folder_id, permission,
    password_hash, download_limit, expires_at
) VALUES (
    $1, $2, $4, $5, $3,
    $6, $7, $8
)
RETURNING id, token, owner_id, file_id, folder_id, permission, password_hash, download_limit, download_count, expires_at, is_active, created_at, updated_at
`

type CreateShareParams struct {
	Token         string             `json:"token"`
	OwnerID       uuid.UUID          `json:"owner_id"`
	Permission    string             `json:"permission"`
	FileID        *uuid.UUID         `json:"file_id"`
	FolderID      *uuid.UUID         `json:"folder_id"`
	PasswordHash  *string            `json:"password_hash"`
	DownloadLimit *int32             `json:"download_limit"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.Token,
		arg.OwnerID,
		arg.Permission,
		arg.FileID,
		arg.FolderID,
		arg.PasswordHash,
		arg.DownloadLimit,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerID,
		&i.FileID,
		&i.FolderID,
		&i.Permission,
		&i.PasswordHash,
		&i.DownloadLimit,
		&i.DownloadCount,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateExpiredShares = `-- name: DeactivateExpiredShares :exec
UPDATE shares SET is_active = FALSE, updated_at = now()
WHERE is_active = TRUE AND expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeactivateExpiredShares(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateExpiredShares)
	return err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT id, token, owner_id, file_id, folder_id, permission, password_hash, download_limit, download_count, expires_at, is_active, created_at, updated_at FROM shares
WHERE token = $1 AND is_active = TRUE
`

func (q *Queries) GetShareByToken(ctx context.Context, token string) (Share, error) {
	row := q.db.QueryRow(ctx, getShareByToken, token)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OwnerID,
		&i.FileID,
		&i.FolderID,
		&i.Permission,
		&i.PasswordHash,
		&i.DownloadLimit,
		&i.DownloadCount,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementShareDownload = `-- name: IncrementShareDownload :exec
UPDATE shares SET download_count = download_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementShareDownload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementShareDownload, id)
	return err
}

const listSharesByOwner = `-- name: ListSharesByOwner :many
SELECT id, token, owner_id, file_id, folder_id, permission, password_hash, download_limit, download_count, expires_at, is_active, created_at, updated_at FROM shares
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSharesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Share, error) {
	rows, err := q.db.Query(ctx, listSharesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.OwnerID,
			&i.FileID,
			&i.FolderID,
			&i.Permission,
			&i.PasswordHash,
			&i.DownloadLimit,
			&i.DownloadCount,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShare = `-- name: RevokeShare :exec
UPDATE shares SET is_active = FALSE, updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type RevokeShareParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) RevokeShare(ctx context.Context, arg RevokeShareParams) error {
	_, err := q.db.Exec(ctx, revokeShare, arg.ID, arg.OwnerID)
	return err
}
