// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const countFilesByOwner = `-- name: CountFilesByOwner :one
SELECT count(*) FROM files WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFilesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFoldersByOwner = `-- name: CountFoldersByOwner :one
SELECT count(*) FROM folders WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFoldersByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashByOwner = `-- name: CountTrashByOwner :one
SELECT count(*) FROM files WHERE owner_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CountTrashByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const largestFilesByOwner = `-- name: LargestFilesByOwner :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY size_bytes DESC
LIMIT $2
`

type LargestFilesByOwnerParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) LargestFilesByOwner(ctx context.Context, arg LargestFilesByOwnerParams) ([]File, error) {
	rows, err := q.db.Query(ctx, largestFilesByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mediaBreakdown = `-- name: MediaBreakdown :many
SELECT
  CASE
    WHEN extension IN ('png','jpg','jpeg','gif','svg','webp','bmp','tiff','ico','avif','heic','psd') THEN 'images'
    WHEN extension IN ('mp4','mov','webm','mkv','avi','flv','ogv') THEN 'video'
    WHEN extension IN ('mp3','wav','flac','ogg','m4a','aac') THEN 'audio'
    WHEN extension IN ('pdf','doc','docx','txt','md','rtf','odt','epub') THEN 'documents'
    WHEN extension IN ('xls','xlsx','xlsm','csv','tsv','ods') THEN 'spreadsheets'
    WHEN extension IN ('ppt','pptx','odp') THEN 'presentations'
    WHEN extension IN ('zip','rar','7z','tar','gz','bz2','xz','iso','dmg') THEN 'archives'
    WHEN extension IN ('js','ts','tsx','jsx','go','py','rb','php','java','c','h','cpp','cs','rs','html','css','json','xml','yaml','yml','sh','sql') THEN 'code'
    ELSE 'other'
  END AS category,
  COALESCE(sum(size_bytes), 0)::bigint AS total,
  count(*) AS files
FROM files
WHERE deleted_at IS NULL
GROUP BY category
ORDER BY total DESC
`

type MediaBreakdownRow struct {
	Category string `json:"category"`
	Total    int64  `json:"total"`
	Files    int64  `json:"files"`
}

func (q *Queries) MediaBreakdown(ctx context.Context) ([]MediaBreakdownRow, error) {
	rows, err := q.db.Query(ctx, mediaBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaBreakdownRow{}
	for rows.Next() {
		var i MediaBreakdownRow
		if err := rows.Scan(&i.Category, &i.Total, &i.Files); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageByUser = `-- name: StorageByUser :many
SELECT u.id, u.username, u.full_name, u.email, r.slug AS role,
       u.storage_used, u.storage_quota,
       (SELECT count(*) FROM files f WHERE f.owner_id = u.id AND f.deleted_at IS NULL) AS file_count
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.deleted_at IS NULL
ORDER BY u.storage_used DESC
`

type StorageByUserRow struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	Role         string    `json:"role"`
	StorageUsed  int64     `json:"storage_used"`
	StorageQuota int64     `json:"storage_quota"`
	FileCount    int64     `json:"file_count"`
}

func (q *Queries) StorageByUser(ctx context.Context) ([]StorageByUserRow, error) {
	rows, err := q.db.Query(ctx, storageByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageByUserRow{}
	for rows.Next() {
		var i StorageByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.StorageUsed,
			&i.StorageQuota,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemFileCount = `-- name: SystemFileCount :one
SELECT count(*) FROM files WHERE deleted_at IS NULL
`

func (q *Queries) SystemFileCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, systemFileCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const systemStorageUsed = `-- name: SystemStorageUsed :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM files WHERE deleted_at IS NULL
`

func (q *Queries) SystemStorageUsed(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, systemStorageUsed)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
