// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
)

const countFilesByOwner = `-- name: CountFilesByOwner :one
SELECT count(*) FROM files WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFilesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFoldersByOwner = `-- name: CountFoldersByOwner :one
SELECT count(*) FROM folders WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFoldersByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashByOwner = `-- name: CountTrashByOwner :one
SELECT count(*) FROM files WHERE owner_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CountTrashByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const largestFilesByOwner = `-- name: LargestFilesByOwner :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY size_bytes DESC
LIMIT $2
`

type LargestFilesByOwnerParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) LargestFilesByOwner(ctx context.Context, arg LargestFilesByOwnerParams) ([]File, error) {
	rows, err := q.db.Query(ctx, largestFilesByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemFileCount = `-- name: SystemFileCount :one
SELECT count(*) FROM files WHERE deleted_at IS NULL
`

func (q *Queries) SystemFileCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, systemFileCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const systemStorageUsed = `-- name: SystemStorageUsed :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM files WHERE deleted_at IS NULL
`

func (q *Queries) SystemStorageUsed(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, systemStorageUsed)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
