// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const addTeamStorage = `-- name: AddTeamStorage :exec
UPDATE teams SET storage_used = GREATEST(0, storage_used + $1) WHERE id = $2
`

type AddTeamStorageParams struct {
	Delta int64     `json:"delta"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AddTeamStorage(ctx context.Context, arg AddTeamStorageParams) error {
	_, err := q.db.Exec(ctx, addTeamStorage, arg.Delta, arg.ID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, description, storage_quota, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, storage_quota, storage_used, created_by, created_at, updated_at
`

type CreateTeamParams struct {
	Name         string     `json:"name"`
	Slug         string     `json:"slug"`
	Description  string     `json:"description"`
	StorageQuota int64      `json:"storage_quota"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.StorageQuota,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, slug, description, storage_quota, storage_used, created_by, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT role FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.user_id, tm.role, u.full_name, u.username, u.email,
       (u.avatar_path IS NOT NULL AND u.avatar_path <> '') AS has_avatar
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.role, u.full_name
`

type ListTeamMembersRow struct {
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	FullName  string    `json:"full_name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	HasAvatar *bool     `json:"has_avatar"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.FullName,
			&i.Username,
			&i.Email,
			&i.HasAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.name, t.slug, t.description, t.storage_quota, t.storage_used, t.created_by, t.created_at, t.updated_at, tm.role AS member_role,
       (SELECT count(*) FROM team_members x WHERE x.team_id = t.id) AS member_count
FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY t.name
`

type ListTeamsForUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  string             `json:"description"`
	StorageQuota int64              `json:"storage_quota"`
	StorageUsed  int64              `json:"storage_used"`
	CreatedBy    *uuid.UUID         `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MemberRole   string             `json:"member_role"`
	MemberCount  int64              `json:"member_count"`
}

func (q *Queries) ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.StorageQuota,
			&i.StorageUsed,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams SET name = $1, description = $2, storage_quota = $3, updated_at = now()
WHERE id = $4
`

type UpdateTeamParams struct {
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	StorageQuota int64     `json:"storage_quota"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam,
		arg.Name,
		arg.Description,
		arg.StorageQuota,
		arg.ID,
	)
	return err
}
