// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllPendingForUser = `-- name: ClearAllPendingForUser :exec
UPDATE files SET transfer_pending = FALSE, transfer_deadline = NULL, transfer_from = NULL, updated_at = now()
WHERE owner_id = $1 AND transfer_pending = TRUE
`

func (q *Queries) ClearAllPendingForUser(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAllPendingForUser, ownerID)
	return err
}

const clearFilePending = `-- name: ClearFilePending :exec
UPDATE files SET transfer_pending = FALSE, transfer_deadline = NULL, transfer_from = NULL, updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type ClearFilePendingParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) ClearFilePending(ctx context.Context, arg ClearFilePendingParams) error {
	_, err := q.db.Exec(ctx, clearFilePending, arg.ID, arg.OwnerID)
	return err
}

const countInheritedFiles = `-- name: CountInheritedFiles :one
SELECT count(*) FROM files
WHERE owner_id = $1 AND transfer_pending = TRUE AND deleted_at IS NULL
`

func (q *Queries) CountInheritedFiles(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInheritedFiles, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentNotifications = `-- name: CountRecentNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND type = $2 AND created_at > $3
`

type CountRecentNotificationsParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentNotifications(ctx context.Context, arg CountRecentNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentNotifications, arg.UserID, arg.Type, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, type, title, body, link, metadata)
VALUES ($1, $2, $3, $4, $6, $5)
`

type CreateNotificationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Type     string    `json:"type"`
	Title    string    `json:"title"`
	Body     string    `json:"body"`
	Metadata []byte    `json:"metadata"`
	Link     *string   `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Metadata,
		arg.Link,
	)
	return err
}

const listInheritedFiles = `-- name: ListInheritedFiles :many
SELECT id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until FROM files
WHERE owner_id = $1 AND transfer_pending = TRUE AND deleted_at IS NULL
ORDER BY transfer_deadline ASC
`

func (q *Queries) ListInheritedFiles(ctx context.Context, ownerID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listInheritedFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Extension,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.IsStarred,
			&i.VersionNo,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCommon,
			&i.TransferPending,
			&i.TransferDeadline,
			&i.TransferFrom,
			&i.LegalHold,
			&i.RetainUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, link, is_read, metadata, created_at, read_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.IsRead,
			&i.Metadata,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = TRUE, read_at = now() WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE, read_at = now() WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const pendingTransfersByUser = `-- name: PendingTransfersByUser :many
SELECT owner_id, count(*) AS pending_count, min(transfer_deadline) AS earliest_deadline
FROM files
WHERE transfer_pending = TRUE AND deleted_at IS NULL
GROUP BY owner_id
`

type PendingTransfersByUserRow struct {
	OwnerID          uuid.UUID   `json:"owner_id"`
	PendingCount     int64       `json:"pending_count"`
	EarliestDeadline interface{} `json:"earliest_deadline"`
}

func (q *Queries) PendingTransfersByUser(ctx context.Context) ([]PendingTransfersByUserRow, error) {
	rows, err := q.db.Query(ctx, pendingTransfersByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingTransfersByUserRow{}
	for rows.Next() {
		var i PendingTransfersByUserRow
		if err := rows.Scan(&i.OwnerID, &i.PendingCount, &i.EarliestDeadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignUserFiles = `-- name: ReassignUserFiles :exec
UPDATE files
SET owner_id = $1, transfer_pending = TRUE, transfer_deadline = $2,
    transfer_from = $3, updated_at = now()
WHERE owner_id = $3 AND deleted_at IS NULL
`

type ReassignUserFilesParams struct {
	ToUser   uuid.UUID          `json:"to_user"`
	Deadline pgtype.Timestamptz `json:"deadline"`
	FromUser *uuid.UUID         `json:"from_user"`
}

func (q *Queries) ReassignUserFiles(ctx context.Context, arg ReassignUserFilesParams) error {
	_, err := q.db.Exec(ctx, reassignUserFiles, arg.ToUser, arg.Deadline, arg.FromUser)
	return err
}

const reassignUserFolders = `-- name: ReassignUserFolders :exec
UPDATE folders SET owner_id = $1, updated_at = now()
WHERE owner_id = $2 AND deleted_at IS NULL
`

type ReassignUserFoldersParams struct {
	ToUser   uuid.UUID `json:"to_user"`
	FromUser uuid.UUID `json:"from_user"`
}

func (q *Queries) ReassignUserFolders(ctx context.Context, arg ReassignUserFoldersParams) error {
	_, err := q.db.Exec(ctx, reassignUserFolders, arg.ToUser, arg.FromUser)
	return err
}
