// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeUpload = `-- name: CompleteUpload :exec
UPDATE uploads
SET status = 'completed', file_id = $2, updated_at = now()
WHERE id = $1
`

type CompleteUploadParams struct {
	ID     uuid.UUID  `json:"id"`
	FileID *uuid.UUID `json:"file_id"`
}

func (q *Queries) CompleteUpload(ctx context.Context, arg CompleteUploadParams) error {
	_, err := q.db.Exec(ctx, completeUpload, arg.ID, arg.FileID)
	return err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (
    user_id, folder_id, filename, total_size, chunk_size,
    total_chunks, temp_key, checksum_sha256, expires_at
) VALUES ($1, $8, $2, $3, $4, $5, $6, $9, $7)
RETURNING id, user_id, folder_id, filename, total_size, chunk_size, total_chunks, uploaded_chunks, received_bytes, temp_key, checksum_sha256, status, file_id, expires_at, created_at, updated_at
`

type CreateUploadParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	Filename    string             `json:"filename"`
	TotalSize   int64              `json:"total_size"`
	ChunkSize   int64              `json:"chunk_size"`
	TotalChunks int32              `json:"total_chunks"`
	TempKey     string             `json:"temp_key"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	FolderID    *uuid.UUID         `json:"folder_id"`
	Checksum    *string            `json:"checksum"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.UserID,
		arg.Filename,
		arg.TotalSize,
		arg.ChunkSize,
		arg.TotalChunks,
		arg.TempKey,
		arg.ExpiresAt,
		arg.FolderID,
		arg.Checksum,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Filename,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.UploadedChunks,
		&i.ReceivedBytes,
		&i.TempKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredUploads = `-- name: DeleteExpiredUploads :many
DELETE FROM uploads
WHERE status = 'in_progress' AND expires_at < now()
RETURNING id, temp_key
`

type DeleteExpiredUploadsRow struct {
	ID      uuid.UUID `json:"id"`
	TempKey string    `json:"temp_key"`
}

func (q *Queries) DeleteExpiredUploads(ctx context.Context) ([]DeleteExpiredUploadsRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteExpiredUploadsRow{}
	for rows.Next() {
		var i DeleteExpiredUploadsRow
		if err := rows.Scan(&i.ID, &i.TempKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpload = `-- name: GetUpload :one
SELECT id, user_id, folder_id, filename, total_size, chunk_size, total_chunks, uploaded_chunks, received_bytes, temp_key, checksum_sha256, status, file_id, expires_at, created_at, updated_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Filename,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.UploadedChunks,
		&i.ReceivedBytes,
		&i.TempKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadForUser = `-- name: GetUploadForUser :one
SELECT id, user_id, folder_id, filename, total_size, chunk_size, total_chunks, uploaded_chunks, received_bytes, temp_key, checksum_sha256, status, file_id, expires_at, created_at, updated_at FROM uploads WHERE id = $1 AND user_id = $2
`

type GetUploadForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUploadForUser(ctx context.Context, arg GetUploadForUserParams) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadForUser, arg.ID, arg.UserID)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Filename,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.UploadedChunks,
		&i.ReceivedBytes,
		&i.TempKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReceivedChunks = `-- name: ListReceivedChunks :many
SELECT chunk_index FROM upload_chunks
WHERE upload_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListReceivedChunks(ctx context.Context, uploadID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listReceivedChunks, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var chunk_index int32
		if err := rows.Scan(&chunk_index); err != nil {
			return nil, err
		}
		items = append(items, chunk_index)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChunk = `-- name: RecordChunk :exec
INSERT INTO upload_chunks (upload_id, chunk_index, size_bytes, checksum)
VALUES ($1, $2, $3, $4)
ON CONFLICT (upload_id, chunk_index) DO NOTHING
`

type RecordChunkParams struct {
	UploadID   uuid.UUID `json:"upload_id"`
	ChunkIndex int32     `json:"chunk_index"`
	SizeBytes  int64     `json:"size_bytes"`
	Checksum   *string   `json:"checksum"`
}

func (q *Queries) RecordChunk(ctx context.Context, arg RecordChunkParams) error {
	_, err := q.db.Exec(ctx, recordChunk,
		arg.UploadID,
		arg.ChunkIndex,
		arg.SizeBytes,
		arg.Checksum,
	)
	return err
}

const setUploadStatus = `-- name: SetUploadStatus :exec
UPDATE uploads SET status = $2, updated_at = now() WHERE id = $1
`

type SetUploadStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) error {
	_, err := q.db.Exec(ctx, setUploadStatus, arg.ID, arg.Status)
	return err
}

const updateUploadProgress = `-- name: UpdateUploadProgress :exec
UPDATE uploads
SET uploaded_chunks = $2, received_bytes = $3, updated_at = now()
WHERE id = $1
`

type UpdateUploadProgressParams struct {
	ID             uuid.UUID `json:"id"`
	UploadedChunks int32     `json:"uploaded_chunks"`
	ReceivedBytes  int64     `json:"received_bytes"`
}

func (q *Queries) UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error {
	_, err := q.db.Exec(ctx, updateUploadProgress, arg.ID, arg.UploadedChunks, arg.ReceivedBytes)
	return err
}
