// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStorageUsed = `-- name: AddStorageUsed :exec
UPDATE users SET storage_used = storage_used + $2, updated_at = now() WHERE id = $1
`

type AddStorageUsedParams struct {
	ID          uuid.UUID `json:"id"`
	StorageUsed int64     `json:"storage_used"`
}

func (q *Queries) AddStorageUsed(ctx context.Context, arg AddStorageUsedParams) error {
	_, err := q.db.Exec(ctx, addStorageUsed, arg.ID, arg.StorageUsed)
	return err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL AND is_active = TRUE
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, username, password_hash, full_name, employee_id,
    department_id, role_id, phone, storage_quota, must_change_pw,
    password_changed_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), $11
)
RETURNING id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language
`

type CreateUserParams struct {
	Email        string     `json:"email"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	EmployeeID   *string    `json:"employee_id"`
	DepartmentID *uuid.UUID `json:"department_id"`
	RoleID       uuid.UUID  `json:"role_id"`
	Phone        *string    `json:"phone"`
	StorageQuota int64      `json:"storage_quota"`
	MustChangePw bool       `json:"must_change_pw"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.EmployeeID,
		arg.DepartmentID,
		arg.RoleID,
		arg.Phone,
		arg.StorageQuota,
		arg.MustChangePw,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getDeletedUserByEmailOrUsername = `-- name: GetDeletedUserByEmailOrUsername :one
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users
WHERE (email = $1 OR username = $2) AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT 1
`

type GetDeletedUserByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetDeletedUserByEmailOrUsername(ctx context.Context, arg GetDeletedUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getDeletedUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT avatar_path FROM users WHERE id = $1
`

func (q *Queries) GetUserAvatar(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, id)
	var avatar_path *string
	err := row.Scan(&avatar_path)
	return avatar_path, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users
WHERE (email = $1 OR username = $1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :one
UPDATE users
SET failed_attempts = failed_attempts + 1, updated_at = now()
WHERE id = $1
RETURNING failed_attempts
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedAttempts, id)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.EmployeeID,
			&i.DepartmentID,
			&i.RoleID,
			&i.AvatarPath,
			&i.Phone,
			&i.StorageQuota,
			&i.StorageUsed,
			&i.IsActive,
			&i.IsLocked,
			&i.FailedAttempts,
			&i.LockedUntil,
			&i.MfaEnabled,
			&i.MfaSecret,
			&i.MustChangePw,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET is_locked = TRUE, locked_until = $2, updated_at = now()
WHERE id = $1
`

type LockUserParams struct {
	ID          uuid.UUID          `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const reactivateUser = `-- name: ReactivateUser :one
UPDATE users SET
    deleted_at = NULL, is_active = TRUE, is_locked = FALSE, failed_attempts = 0,
    email = $1, username = $2, password_hash = $3,
    full_name = $4, role_id = $5, storage_quota = $6,
    employee_id = $7, phone = $8, must_change_pw = TRUE, updated_at = now()
WHERE id = $9
RETURNING id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language
`

type ReactivateUserParams struct {
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	RoleID       uuid.UUID `json:"role_id"`
	StorageQuota int64     `json:"storage_quota"`
	EmployeeID   *string   `json:"employee_id"`
	Phone        *string   `json:"phone"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) ReactivateUser(ctx context.Context, arg ReactivateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, reactivateUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.RoleID,
		arg.StorageQuota,
		arg.EmployeeID,
		arg.Phone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const resetUserPassword = `-- name: ResetUserPassword :exec
UPDATE users
SET password_hash = $2, password_changed_at = now(), must_change_pw = TRUE, updated_at = now()
WHERE id = $1
`

type ResetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

// Admin reset: force the user to change it on next login.
func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, resetUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const setUserAvatar = `-- name: SetUserAvatar :exec
UPDATE users SET avatar_path = $2, updated_at = now() WHERE id = $1
`

type SetUserAvatarParams struct {
	ID         uuid.UUID `json:"id"`
	AvatarPath *string   `json:"avatar_path"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error {
	_, err := q.db.Exec(ctx, setUserAvatar, arg.ID, arg.AvatarPath)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
UPDATE users SET language = $1, updated_at = now() WHERE id = $2
`

type SetUserLanguageParams struct {
	Language string    `json:"language"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.Exec(ctx, setUserLanguage, arg.Language, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2, password_changed_at = now(), must_change_pw = FALSE, updated_at = now()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), is_active = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users
SET is_locked = FALSE, locked_until = NULL, failed_attempts = 0, updated_at = now()
WHERE id = $1
`

func (q *Queries) UnlockUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlockUser, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = now(), failed_attempts = 0, updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = $2, phone = $3, department_id = $4, avatar_path = $5, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, username, password_hash, full_name, employee_id, department_id, role_id, avatar_path, phone, storage_quota, storage_used, is_active, is_locked, failed_attempts, locked_until, mfa_enabled, mfa_secret, must_change_pw, password_changed_at, last_login_at, created_by, created_at, updated_at, deleted_at, language
`

type UpdateUserProfileParams struct {
	ID           uuid.UUID  `json:"id"`
	FullName     string     `json:"full_name"`
	Phone        *string    `json:"phone"`
	DepartmentID *uuid.UUID `json:"department_id"`
	AvatarPath   *string    `json:"avatar_path"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.DepartmentID,
		arg.AvatarPath,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.EmployeeID,
		&i.DepartmentID,
		&i.RoleID,
		&i.AvatarPath,
		&i.Phone,
		&i.StorageQuota,
		&i.StorageUsed,
		&i.IsActive,
		&i.IsLocked,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.MustChangePw,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Language,
	)
	return i, err
}

const updateUserQuota = `-- name: UpdateUserQuota :exec
UPDATE users SET storage_quota = $2, updated_at = now() WHERE id = $1
`

type UpdateUserQuotaParams struct {
	ID           uuid.UUID `json:"id"`
	StorageQuota int64     `json:"storage_quota"`
}

func (q *Queries) UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error {
	_, err := q.db.Exec(ctx, updateUserQuota, arg.ID, arg.StorageQuota)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role_id = $2, updated_at = now() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID     uuid.UUID `json:"id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.RoleID)
	return err
}
