// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package sftpdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpFileContent = `-- name: BumpFileContent :one
UPDATE files
SET storage_key = $1,
    size_bytes = $2,
    checksum_sha256 = $3,
    version_no = version_no + 1,
    updated_at = now()
WHERE id = $4
RETURNING id, owner_id, folder_id, name, extension, mime_type, size_bytes, checksum_sha256, storage_key, thumbnail_key, is_starred, version_no, download_count, created_at, updated_at, deleted_at, is_common, transfer_pending, transfer_deadline, transfer_from, legal_hold, retain_until
`

type BumpFileContentParams struct {
	StorageKey     string    `json:"storage_key"`
	SizeBytes      int64     `json:"size_bytes"`
	ChecksumSha256 *string   `json:"checksum_sha256"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) BumpFileContent(ctx context.Context, arg BumpFileContentParams) (File, error) {
	row := q.db.QueryRow(ctx, bumpFileContent,
		arg.StorageKey,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Extension,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.IsStarred,
		&i.VersionNo,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCommon,
		&i.TransferPending,
		&i.TransferDeadline,
		&i.TransferFrom,
		&i.LegalHold,
		&i.RetainUntil,
	)
	return i, err
}

const getFileVersion = `-- name: GetFileVersion :one
SELECT version_no, size_bytes, checksum_sha256, storage_key
FROM file_versions
WHERE file_id = $1 AND version_no = $2
`

type GetFileVersionParams struct {
	FileID    uuid.UUID `json:"file_id"`
	VersionNo int32     `json:"version_no"`
}

type GetFileVersionRow struct {
	VersionNo      int32   `json:"version_no"`
	SizeBytes      int64   `json:"size_bytes"`
	ChecksumSha256 *string `json:"checksum_sha256"`
	StorageKey     string  `json:"storage_key"`
}

func (q *Queries) GetFileVersion(ctx context.Context, arg GetFileVersionParams) (GetFileVersionRow, error) {
	row := q.db.QueryRow(ctx, getFileVersion, arg.FileID, arg.VersionNo)
	var i GetFileVersionRow
	err := row.Scan(
		&i.VersionNo,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageKey,
	)
	return i, err
}

const insertFileVersion = `-- name: InsertFileVersion :exec
INSERT INTO file_versions (file_id, version_no, size_bytes, checksum_sha256, storage_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (file_id, version_no) DO NOTHING
`

type InsertFileVersionParams struct {
	FileID         uuid.UUID  `json:"file_id"`
	VersionNo      int32      `json:"version_no"`
	SizeBytes      int64      `json:"size_bytes"`
	ChecksumSha256 *string    `json:"checksum_sha256"`
	StorageKey     string     `json:"storage_key"`
	CreatedBy      *uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertFileVersion(ctx context.Context, arg InsertFileVersionParams) error {
	_, err := q.db.Exec(ctx, insertFileVersion,
		arg.FileID,
		arg.VersionNo,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StorageKey,
		arg.CreatedBy,
	)
	return err
}

const listFileVersions = `-- name: ListFileVersions :many
SELECT v.version_no, v.size_bytes, v.checksum_sha256, v.created_at,
       u.full_name AS author_name, u.username AS author_username
FROM file_versions v
LEFT JOIN users u ON u.id = v.created_by
WHERE v.file_id = $1
ORDER BY v.version_no DESC
`

type ListFileVersionsRow struct {
	VersionNo      int32              `json:"version_no"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 *string            `json:"checksum_sha256"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthorName     *string            `json:"author_name"`
	AuthorUsername *string            `json:"author_username"`
}

func (q *Queries) ListFileVersions(ctx context.Context, fileID uuid.UUID) ([]ListFileVersionsRow, error) {
	rows, err := q.db.Query(ctx, listFileVersions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileVersionsRow{}
	for rows.Next() {
		var i ListFileVersionsRow
		if err := rows.Scan(
			&i.VersionNo,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
